Fix/background color auto
thumbor/thumbor pull request #1489
Opened 2022-10-01 22:14 UTC by siqueira-ec

This PR fixes #1469 

I extracted the method `get_median_color` from class `Filter` from `fill` to increase the use flexibility and proper added the test case and fixture.

2022-10-02 17:06 UTC, scorphus requested changes
Thanks for contributing, @siqueira-ec. Please consider my comments below.

2022-10-02 17:06 UTC, scorphus commented on tests/filters/test_background_color.py
> +            config_context=config_context,
In order to decrease the amount of repeated code, would you consider creating a new `config_context` method and having this line — and the respective one of the test above — read the following?
```suggestion
            config_context=self.config_context,
```

2022-10-02 22:22 UTC, siqueira-ec commented
@scorphus 

Thank you for reviewing.

All comments resolved! Could you please check again?

2022-10-02 22:39 UTC, scorphus requested changes

2022-10-02 22:39 UTC, scorphus commented on tests/filters/test_background_color.py
> +    def config_context(context):
```suggestion
    def config_context(self, context):
```

Otherwise it'll fail.

Are you running testes locally?

2022-10-02 22:59 UTC, siqueira-ec commented
Forgot to commit and push that modification, sorry @scorphus 

Done.

2022-10-03 19:27 UTC, scorphus requested changes

2022-10-03 20:33 UTC, siqueira-ec commented
Done! @scorphus

2022-10-03 20:42 UTC, scorphus commented
@siqueira-ec, parece que o email que vc utilizou para criar os commits não está atrelado à sua conta no GitHub.

2022-10-03 20:45 UTC, siqueira-ec commented
@scorphus Eu vi aqui que o local tava com email do serviço. Posso vincular à minha conta que vai contar na ferramenta de vocês ou preciso passar o email vinculado e vocês desenrolam daí?

2022-10-03 20:52 UTC, scorphus commented
Vai depender mais do que vc preferir. Pro projeto em si não faz tanta diferença. Mas a contribuição fica atrelada ao seu usuário, e isso pode ser interessante pra vc.

p.s. caramba, eu nem percebi que escrevi em PT, só quando comecei a ler a sua msg. 😄

2022-10-03 21:02 UTC, scorphus commented
Let's go back to English, my bad.

Let's see how it goes after the commits get squashed. Maybe you won't need to register the new email address — or you can always do it later.

2022-10-03 21:04 UTC, scorphus approved these changes
Thanks for contributing and fixing #1469, @siqueira-ec!

2022-10-03 21:04 UTC, scorphus commented on tests/filters/test_background_color.py
> +
👍

2022-10-03 21:04 UTC, scorphus commented on thumbor/engines/pil.py
> +
🙌

2022-10-03 21:06 UTC, merged

2022-10-03 21:10 UTC, siqueira-ec commented
@scorphus

I added the email used to commit these changes in my GitHub account.

To participate in Globo Hacktoberfest i must set it as the main email?

Or i must change the email on event profile settings dashboard?

I already met the event criteria (2 PR's and 1 accepted). Will it be a problem?

On event dashboard, it counts as 0 PR's.

2022-10-03 21:18 UTC, scorphus commented
YAY! Good job on completing the challenge! 🎉 

I'm not quite sure about Globo's Hacktoberfest, but I believe it won't be a problem as your GH user is attached to this PR. Let me ping @marcelometal, as he might have a say on that.

As to DigitalOcean's Hacktoberfest, give it a few minutes and it should update.

2022-10-03 21:23 UTC, siqueira-ec commented
> YAY! Good job on completing the challenge! tada
> 
> I'm not quite sure about Globo's Hacktoberfest, but I believe it won't be a problem as your GH user is attached to this PR. Let me ping @marcelometal, as he might have a say on that.
> 
> As to DigitalOcean's Hacktoberfest, give it a few minutes and it should update.

As to DigitalOcean's, already done, haha. My doubt is just about Globo's, as my PR's are not appearing there.